services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - sftp_upload:/home/devuser/upload
    command: devuser:devpass:1001

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sftp_index
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - sftp
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sftp_index
    volumes:
      - ./downloads:/app/downloads

volumes:
  sftp_upload:
  mysql_data: